# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Romina Caraba-Thampi
tagline:          'Personal Page'
description:      'Machine Learning Engineer and Data Analyst'
baseurl:          https://rominacarabathampi.ca/ # the subpath of your site, e.g. /blog/
url:              https://rominacarabathampi.ca/ # the base hostname & protocol for your site

author:
  name:           'Romina Caraba-Thampi'
  url:            https://www.linkedin.com/in/rominacarabathampi/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rominacarabathampi/
