# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Romina Caraba-Thampi
tagline:          'Personal Page'
description:      'Enthusiastic Machine Learning Engineer eager to contribute to team success through hard work, attention to detail and excellent organizational skills. Clear understanding of probability, statistics, analysis and training in Python. Motivated to learn, grow and excel in the tech industry.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Romina Caraba-Thampi'
  url:            https://www.linkedin.com/in/rominacarabathampi/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rominacarabathampi/personal_page
